# Generated by Django 2.2.1 on 2019-06-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laptop_id', models.CharField(max_length=264, unique=True)),
                ('person_id_id', models.CharField(max_length=264, unique=True)),
                ('person_name', models.CharField(max_length=264, unique=True)),
                ('issue_date', models.DateField()),
                ('return_date', models.DateField()),
            ],
        ),
    ]
